services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 6543:5432
    volumes:
      - ./etc/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

# volumes:
#   pg_volume:
